name: 'test'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  tests:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Set up JDK 17'
        uses: 'actions/setup-java@v3'
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Run Tests'
        run: 'mvn clean test'
